### ISSUE TITLE
Factories with Arguments

### ISSUE THREAD

**Issue by digitalkaoz** [KnisterPeter/tsdi#119]
it should be possible to pass argument to factories:

```ts
@Component()
class Foo {
    
    @Factory()
    public static create(foo, bar){
        return new Foo(foo, bar);
    }
}
```

maybe it could be solved right now when `foo` and `bar` are Container properties?! But putting them into the container is not really cool i think

**Comment by KnisterPeter** [comment]
Where should the value come from? The factory is called by TSDI so the container need to know how to resolve these parameters.

**Comment by digitalkaoz** [comment]
thats exactly the problem ;)

i guess this works right now?

```ts
@Component()
TSDI.addProperty('foo', 'foo');
class Foo {
    
    @Factory()
    public static create(@Inject('foo') foo, @Inject('bar') bar){
        return new Foo(foo, bar);
    }
}
```

**Comment by KnisterPeter** [comment]
Yes, that might work but kind of undermines dependency injection, eh?
You could more easily write this:
```js
@Component()
class Foo {
    
    @Factory()
    public static create(){
        return new Foo('foo', 'bar');
    }
}
```
If you put the parameters directly above the factory (even hardcoded) then it would be more easy to have a real static factory.

Otherwise I would propose to create a config file, on startup add that as properties to the container and then use your factory with '@Inject' decorators. That should work (if not, its a bug or requires a new feature).
