### ISSUE TITLE
@Require Decorator

### ISSUE THREAD

**Issue by digitalkaoz** [KnisterPeter/tsdi#120]
like this one https://github.com/pleerock/typedi#injecting-third-party-dependencies-experimental

**Comment by KnisterPeter** [comment]
I'm not sure how maintainable this feature is from code perspective of the users.
I think it would be better to use the `register` API to provide these dependencies to the container instead of spreading require decorators or statements throughout the application.

Can you please but a bit more detail or use cases in here?
