### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by Nukesor** [KnisterPeter/tsdi#1596]
Hey @KnisterPeter 

I just wanted to get a quick and honest assessment on the state of this project.
There haven't been any releases since roughly two years and barely any activity besides lots of dependency updates.

Is this something you would encourage to use in a production environment or rather for personal/hobby projects?

**Comment by KnisterPeter** [comment]
Hi @Nukesor, the project is fine and maintained. As far as I can tell it is used by some companies in their production applications.

> There haven't been any releases since roughly two years and barely any activity besides lots of dependency updates.

I would consider the current version of the project done. There are no features missing from my perspective. But there are known limitations.

I started to implement a major rewrite which I then dropped, because:
- I lost my use-case for the rewrite
- EcmaScript decorator proposal has changed very much and handling of typescript decorators is still experimental

> Is this something you would encourage to use in a production environment or rather for personal/hobby projects?

This is most likely up to you. I do not sell enterprise support for this. It's open source and fairly simple to understand and fix if there are issues in there.
As stated above, there are companies using it in production, but you have to decide for your case.

**Comment by Nukesor** [comment]
Thanks for your assessment! This already helps a lot.
