### ISSUE TITLE
Asynchronous component initializers

### ISSUE THREAD

**Issue by Prior99** [KnisterPeter/tsdi#208]
# Feature Request: Asynchronous Factories

I am using TSDI to inject a database across my application. For this I am using a factory, think:

```ts
@component
class DatabaseFactory {
    private databaseConnection: DatabaseConnection;

    @initialize
    connect() {
        this.databaseConnection = new DatabaseConnection();
    }

    @factory
    getDatabaseConnection(): DatabaseConnection {
        return this.databaseConnection;
    }
}
```

However, the database initialization is asynchronous, and that's where the problems start:

```ts
@component
class DatabaseFactory {
    private databaseConnection: DatabaseConnection;

    @initialize
    async connect() {
        this.databaseConnection = await connectToDatabase();
    }

    @factory
    getDatabaseConnection(): DatabaseConnection {
        return this.databaseConnection;
    }
}

@component({ eager: true })
class Api {
    @inject private db: DatabaseConnection;

    @initialize
    public initialize() {
        this.db.query(...); // `db` is now `undefined`.
    }
}
```

It'd be cool, if this could somehow be solved.

**Comment by KnisterPeter** [comment]
@Prior99 Thanks for reporting. I'll have to think about it.
Its a good use case which will require a bit more API I think.

Could be a problem in `tsdi` object graph creation.

**Comment by KnisterPeter** [comment]
My idea to solve this is to wait for all injects to be created and have their initializer executed. Initializers which return a promise should be awaited in this case. 

The biggest problem right now is the default lazy injection. The `db` above need to be eager injected instead of lazy, so the component is created before first access and could be awaited.

**Comment by KnisterPeter** [comment]
@Prior99 As of #209 this issue is partially solved. The part missing are the factories. By the synchronous nature of the `new` keyword in javascript and therefore the synchronous nature of dependency injection it is not possible to implement asynchronous factories.

You may work around this with this pattern:

```ts
@component
class Database {
    private databaseConnection: DatabaseConnection;

    @initialize
    async connect() {
        this.databaseConnection = await connectToDatabase();
    }

    get connection(): DatabaseConnection {
        return this.databaseConnection;
    }
}

@component({ eager: true })
class Api {
    @inject private db: Database;

    @initialize
    public initialize() {
        this.db.connection.query(...); // `db` is now `undefined`.
    }
}
```

Since `Api.initialize()` is only called if all injected dependencies are itself done you can be sure that `this.db.connection` is ready in your example.
Hope that help a bit.
